import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About | Next",
    description: 'Generated by create next app',
}

function AboutPage() {
return (
    <h1>ABOUT PAGE</h1>
);
}
export default AboutPage;