import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderPage from './components/Header/page'
import FooterPage from './components/Footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderPage />
        <main>{children}</main>
        <FooterPage />
        </body>
    </html>
  )
}
